manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: efogdev
      url-base: https://github.com/efogdev
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson
      revision: core/move-to-zephyr-4-1
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: efogdev
      revision: zephyr-4.1
    - name: zmk-pointer-2s-mixer
      remote: efogdev
      revision: refactoring/twist-v2
    - name: zmk-axis-clamper
      remote: efogdev
      revision: main
    - name: zmk-report-rate-limit
      remote: efogdev
      revision: main
    - name: zmk-ec11-ish-driver
      remote: efogdev
      revision: main
    - name: zmk-auto-hold
      remote: efogdev
      revision: main
  self:
    path: config
